In [6]:
pip install path

Collecting path
  Downloading path-15.1.2-py3-none-any.whl (21 kB)
Installing collected packages: path
Successfully installed path-15.1.2
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\parom\AppData\Local\Programs\Python\Python37\python.exe -m pip install --upgrade pip' command.

In [7]:
# Machine Learning Model: Logistic Regression

# Import dependencies
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import sklearn as skl
import numpy as np
from path import Path

In [8]:
#Importing the data
# Import the cleaned, combined CSV file and read it into a Pandas DataFrame
data = Path('./titles_updated.csv')
titles_df = pd.read_csv(data)
titles_df

,Title,type,country,date_added,release_year,rating,duration,description,IMDb,Genre,Avg Rating per Genre,Growth Outcome
0,3%,TV Show,Brazil,2020-08-14,2020,TV-MA,4 Seasons,In a future where the elite inhabit an island ...,7.4,Drama,6.57,0
1,7:19,Movie,Mexico,2016-12-23,2016,TV-MA,93 min,After a devastating earthquake hits Mexico Cit...,6.0,Drama,6.57,0
2,23:59,Movie,Singapore,2018-12-20,2011,R,78 min,"When an army recruit is found dead, his fellow...",4.7,Horror,5.52,0
3,9,Movie,United States,2017-11-16,2009,PG-13,80 min,"In a postapocalyptic world, rag-doll robots hi...",7.1,Action & Adventure,6.14,0
4,21,Movie,United States,2020-01-01,2008,PG-13,123 min,A brilliant group of students become card-coun...,6.8,Drama,6.57,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3886,Zona Rosa,TV Show,Mexico,2019-11-26,2019,TV-MA,1 Season,An assortment of talent takes the stage for a ...,5.8,Comedy,6.34,0
3887,Zoo,Movie,India,2018-07-01,2018,TV-MA,94 min,A drug dealer starts having doubts about his t...,6.8,Drama,6.57,0
3888,Zoom,Movie,United States,2020-01-11,2006,PG,88 min,"Dragged from civilian life, a former superhero...",4.4,Comedy,6.34,0
3889,Zubaan,Movie,India,2019-03-02,2015,TV-14,111 min,A scrappy but poor boy worms his way into a ty...,6.1,Drama,6.57,0
3890,Zumbo's Just Desserts,TV Show,Australia,2020-10-31,2019,TV-PG,1 Season,Dessert wizard Adriano Zumbo looks for the nex...,6.9,Reality,6.48,0

In [9]:
# Drop the description column because it does not need to be encoded
titles_df = titles_df.drop(['description'], axis = 1)
titles_df

,Title,type,country,date_added,release_year,rating,duration,IMDb,Genre,Avg Rating per Genre,Growth Outcome
0,3%,TV Show,Brazil,2020-08-14,2020,TV-MA,4 Seasons,7.4,Drama,6.57,0
1,7:19,Movie,Mexico,2016-12-23,2016,TV-MA,93 min,6.0,Drama,6.57,0
2,23:59,Movie,Singapore,2018-12-20,2011,R,78 min,4.7,Horror,5.52,0
3,9,Movie,United States,2017-11-16,2009,PG-13,80 min,7.1,Action & Adventure,6.14,0
4,21,Movie,United States,2020-01-01,2008,PG-13,123 min,6.8,Drama,6.57,0
...,...,...,...,...,...,...,...,...,...,...,...
3886,Zona Rosa,TV Show,Mexico,2019-11-26,2019,TV-MA,1 Season,5.8,Comedy,6.34,0
3887,Zoo,Movie,India,2018-07-01,2018,TV-MA,94 min,6.8,Drama,6.57,0
3888,Zoom,Movie,United States,2020-01-11,2006,PG,88 min,4.4,Comedy,6.34,0
3889,Zubaan,Movie,India,2019-03-02,2015,TV-14,111 min,6.1,Drama,6.57,0
3890,Zumbo's Just Desserts,TV Show,Australia,2020-10-31,2019,TV-PG,1 Season,6.9,Reality,6.48,0

In [10]:
# Generate our categorical variable list
titles_cat = titles_df.dtypes[titles_df.dtypes == "object"].index.tolist()

In [11]:
# Check the number of unique values in each column
titles_df[titles_cat].nunique()

Title         3885
type             2
country        442
date_added    1176
rating          14
duration       183
Genre           15
dtype: int64

In [12]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [13]:
# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(titles_df[titles_cat]))

In [14]:
# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(titles_cat)
encode_df

,Title_#Rucker50,Title_#Selfie,Title_#blackAF,Title_#cats_the_mewvie,Title_#realityhigh,Title_(T)ERROR,Title_10 jours en or,Title_100 Meters,Title_100% Hotter,Title_1000 Rupee Note,...,Genre_Documentaries,Genre_Drama,Genre_Horror,Genre_Musicals,Genre_Mystery,Genre_Reality,Genre_Romance,Genre_Sci-Fi & Fantasy,Genre_Teen,Genre_Thrillers
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3886,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3887,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3888,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3889,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3890,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [15]:
# Merge one-hot encoded features and drop the originals
titles_df = titles_df.merge(encode_df,left_index=True, right_index=True)
titles_df = titles_df.drop(titles_cat,1)
titles_df

,release_year,IMDb,Avg Rating per Genre,Growth Outcome,Title_#Rucker50,Title_#Selfie,Title_#blackAF,Title_#cats_the_mewvie,Title_#realityhigh,Title_(T)ERROR,...,Genre_Documentaries,Genre_Drama,Genre_Horror,Genre_Musicals,Genre_Mystery,Genre_Reality,Genre_Romance,Genre_Sci-Fi & Fantasy,Genre_Teen,Genre_Thrillers
0,2020,7.4,6.57,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2016,6.0,6.57,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2011,4.7,5.52,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2009,7.1,6.14,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2008,6.8,6.57,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3886,2019,5.8,6.34,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3887,2018,6.8,6.57,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3888,2006,4.4,6.34,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3889,2015,6.1,6.57,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3890,2019,6.9,6.48,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [16]:
#Setting up the model

# Separate the Features(X) from the Target (y)
y = titles_df["Growth Outcome"]
X = titles_df.drop(columns = "Growth Outcome")

In [17]:

# Split our data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
X_train.shape

(2918, 5720)

In [22]:
# Create a Logistic Regression Model
classifier = LogisticRegression(solver='lbfgs', random_state=1, max_iter=200)
classifier

LogisticRegression(max_iter=200, random_state=1)

In [23]:
# Fit(train) our model using the training data
classifier.fit(X_train, y_train)

C:\Users\parom\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(max_iter=200, random_state=1)

In [24]:
# Predict outcomes for data set
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       0
1            0       0
2            0       0
3            0       0
4            0       0
5            1       1
6            0       0
7            0       0
8            0       0
9            0       0
10           0       0
11           0       0
12           0       0
13           0       0
14           0       0
15           0       0
16           0       0
17           0       0
18           0       0
19           0       0

In [25]:
# Validate the model using the test data
accuracy_score(y_test, y_pred)

0.998972250770812